export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_CAMUNDA_REQUEST = "AUTH_CAMUNDA_REQUEST";
export const AUTH_CAMUNDA_SUCCESS = "AUTH_CAMUNDA_SUCCESS";
export const AUTH_CAMUNDA_ERROR = "AUTH_CAMUNDA_ERROR";
export const AUTH_CAMUNDA_LOGOUT = "AUTH_CAMUNDA_LOGOUT";
