export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";

export const USER_CAMUNDA_REQUEST = "USER_CAMUNDA_REQUEST";
export const USER_CAMUNDA_SUCCESS = "USER_CAMUNDA_SUCCESS";
export const USER_CAMUNDA_ERROR = "USER_CAMUNDA_ERROR";
